Repository pivotal-cf/docs-tas-kubernetes, pull requests merged in 2020-10, with the labels that each got.

#44 Feat: LoadBalancer configuration options
  configuring-installation-values.html.md.erb
Labels: scheduled

#43 Update cert docs to show how to add two+ certs
  configuring-installation-values.html.md.erb
Labels: scheduled

#47 Change apps_manager.resources.instances default to 2
  configuring-apps-manager.html.md.erb
Labels: in progress

#46 Fix private registry installation procedure
  configuring-sys-image-registry.html.md.erb
  installing-tas-for-kubernetes.html.md.erb
Labels: scheduled

#48 Change 'Enterprise PKS' to 'TKGI' to reflect the branding change
  _limitation_notes.html.md.erb
  configuring-default-storage.html.md.erb
  configuring-installation-values.html.md.erb
  installing-command-line-tools.html.md.erb
  preparing-kubernetes-cluster.html.md.erb
  preparing-to-install-tas-for-kubernetes.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#49 Update generate-values instructions to match new process
  installing-tas-for-kubernetes.html.md.erb
Labels: in progress

#50 Add instructions for cluster-detect script
  installing-tas-for-kubernetes.html.md.erb
Labels: in progress

#52 Update configuring apps manager using the sample values file
  configuring-apps-manager.html.md.erb
Labels: scheduled

#53 Fix private registry installation procedure #2
  configuring-sys-image-registry.html.md.erb
  installing-tas-for-kubernetes.html.md.erb
Labels: in progress

#56 Fix: add cluster detect script instructions for private registry install
  installing-tas-for-kubernetes.html.md.erb
Labels: unscheduled

#57 Getting the scaling instruction page in place
  index-admin.html.md.erb
  scaling-tas-for-kubernetes.html.md.erb
Labels: unscheduled

#60 Cleanup some of the instructions to latest
  bandr-restore-manual.html.md.erb
Labels: unscheduled

#54 improving the technical accuracy of the default storage class topic
  configuring-default-storage.html.md.erb
  index-prepare.html.md.erb
  installing-default-storage-class.html.md.erb
  preparing-kubernetes-cluster.html.md.erb
Labels: in progress

#55 Removes mentions of apps manager scaling settings
  configuring-apps-manager.html.md.erb
Labels: scheduled

#58 Update docs to clarify that app and system domains should be unique
  configuring-installation-values.html.md.erb
  installing-tas-for-kubernetes.html.md.erb
Labels: in progress

#63 Updated correct config file to look for admin pwd
  installing-tas-for-kubernetes.html.md.erb
Labels: scheduled

#59 Add app log destinations to installation values guide
  configuring-installation-values.html.md.erb
Labels: in progress

#61 Update docs to state that cf cli v7.0.1 or later is required
  installing-tas-for-kubernetes.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#64 Fixed minor formatting in warning message
  installing-tas-for-kubernetes.html.md.erb
Labels: scheduled
