Repository pivotal-cf/docs-tas-kubernetes, pull requests merged in 2020-11, with the labels that each got.

#65 Update bandr-backup-manual.html.md.erb
  bandr-backup-manual.html.md.erb
Labels: scheduled

#66 removes all usages of the `jq` tool. It's not needed
  bandr-configuration.html.md.erb
Labels: in progress

#67 Added warning message that blobstore key cannot be rotated
  installing-tas-for-kubernetes.html.md.erb
Labels: in progress

#68 TPG has fixed a bug - updating docs
  bandr-restore-manual.html.md.erb
Labels: in progress

#69 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#70 Update configuring-system-databases.html.md.erb
  configuring-system-databases.html.md.erb
Labels: scheduled

#71 Update configuring-system-databases.html.md.erb
  configuring-system-databases.html.md.erb
Labels: scheduled

#72 Remove placeholder pod names in favour of the real thing
  bandr-configuration.html.md.erb
Labels: in progress

#73 kubectl command to get storageclass correction
  preparing-kubernetes-cluster.html.md.erb
Labels: unscheduled

#74 Update configuring-system-databases.html.md.erb
  configuring-system-databases.html.md.erb
Labels: scheduled

#75 update instructions to work with Tanzu Postgres 1.0
  bandr-configuration.html.md.erb
Labels: in progress

#76 B and R - Remove snapshot instructions
  bandr-backup-manual.html.md.erb
Labels: in progress

#77 TPG 1.0 restore changes for restore
  bandr-restore-manual.html.md.erb
Labels: in progress

#62 175172851 update image relocation instructions
  configuring-sys-image-registry.html.md.erb
Labels: in progress

#78 Update B/R docs to use vanilla velero
  bandr-backup-manual.html.md.erb
  bandr-configuration.html.md.erb
  bandr-restore-manual.html.md.erb
Labels: unscheduled

#79 Updates to Rel 0.6 Release Notes
  release-notes.html.md.erb
Labels: in progress
