Repository pivotal-cf/docs-tas-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#31 Clarify how directories relate to each other
  configuring-installation-values.html.md.erb
Labels: scheduled

#33 Add documentation for fetching the version
  installing-tas-for-kubernetes.html.md.erb
Labels: in progress

#32 update apps-manager docs to reflect invitations default
  configuring-apps-manager.html.md.erb
Labels: scheduled

#36 Update 0.4.0 release notes
  release-notes.html.md.erb
Labels: scheduled

#35 change the file name to reflect the other config files
  optional-image-relocation.html.md.erb
Labels: scheduled

#34 Apps Manager: Remove invitation service configuration
  configuring-apps-manager.html.md.erb
Labels: scheduled

#38 updated the configuration process
  configuring-app-image-registry.html.md.erb
  configuring-apps-manager.html.md.erb
  configuring-external-database.html.md.erb
  configuring-installation-values.html.md.erb
  configuring-sys-image-registry.html.md.erb
  configuring-system-databases.html.md.erb
  index-install.html.md.erb
  installing-tas-for-kubernetes.html.md.erb
  preparing-to-install-tas-for-kubernetes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#37 add list of unsupported features for appsmanager
  release-notes.html.md.erb
Labels: unscheduled

#39 tas for k8s now requires an external database
  configuring-default-storage.html.md.erb
  configuring-installation-values.html.md.erb
  index-install.html.md.erb
  preparing-kubernetes-cluster.html.md.erb
Labels: unscheduled

#40 feat: give specific instructions for installing tanzu postgres
  configuring-system-databases.html.md.erb
Labels: unscheduled

#41 Update system database names in kubectl example
  configuring-system-databases.html.md.erb
Labels: in progress
