Repository pivotal-cf/docs-tas-kubernetes, pull requests merged in 2021-01, with the labels that each got.

#82 Update configuring-installation-values.html.md.erb
  configuring-installation-values.html.md.erb
Labels: scheduled

#83 Minor doc edits for the bandr process
  bandr-backup-manual.html.md.erb
  bandr-restore-manual.html.md.erb
Labels: scheduled

#84 document known issue with the compare-backup-metadata script
  bandr-restore-manual.html.md.erb
Labels: in progress

#85 update release notes in preparation for 0.7 beta
  release-notes.html.md.erb
Labels: unscheduled

#86 update 0.7 release notes
  release-notes.html.md.erb
Labels: unscheduled

#88 Update configuring-installation-values.html.md.erb
  configuring-installation-values.html.md.erb
Labels: unscheduled
